# Generated by Django 3.2.5 on 2024-03-15 12:44

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('schools', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='MailLog',
            fields=[
                ('mail_id', models.AutoField(primary_key=True, serialize=False)),
                ('mFrom', models.EmailField(max_length=254)),
                ('to', models.EmailField(max_length=254)),
                ('subject', models.CharField(max_length=255)),
                ('body', models.TextField()),
                ('sent_at', models.DateTimeField(auto_now_add=True)),
                ('queue', models.CharField(max_length=50)),
                ('principal', models.EmailField(max_length=254)),
                ('school', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='schools.school')),
            ],
        ),
    ]
