# Generated by Django 3.2.5 on 2024-03-13 13:36

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('schools', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='school',
            name='video',
            field=models.FileField(blank=True, null=True, upload_to='landing_page', validators=[django.core.validators.FileExtensionValidator(['mp4', 'avi', 'mov'])]),
        ),
    ]
