# Generated by Django 5.0.3 on 2024-03-19 13:58

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('schools', '0002_alter_events_event_image_eventimages'),
    ]

    operations = [
        migrations.AlterField(
            model_name='eventimages',
            name='image',
            field=models.ImageField(blank=True, default=' ', null=True, upload_to='img', validators=[django.core.validators.FileExtensionValidator(['jpg', 'jpeg', 'png'])]),
        ),
    ]
