# Generated by Django 3.2.5 on 2024-03-22 10:35

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('schools', '0003_auto_20240321_1207'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='events',
            name='school',
        ),
        migrations.RemoveField(
            model_name='eventspeaker',
            name='events',
        ),
        migrations.DeleteModel(
            name='EventImages',
        ),
        migrations.DeleteModel(
            name='Events',
        ),
        migrations.DeleteModel(
            name='EventSpeaker',
        ),
    ]
