# Generated by Django 3.2.5 on 2024-03-26 11:21

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('schools', '0003_mymodel'),
    ]

    operations = [
        migrations.DeleteModel(
            name='MyModel',
        ),
    ]
