# Generated by Django 5.0.3 on 2024-03-19 15:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('schools', '0005_eventimages_thumbnail'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='eventimages',
            name='thumbnail',
        ),
        migrations.AddField(
            model_name='events',
            name='thumbnail',
            field=models.ImageField(blank=True, null=True, upload_to='img/thumbnails'),
        ),
    ]
