# Generated by Django 3.2.6 on 2021-08-28 15:46

from django.db import migrations, models
import django.db.models.deletion
import tinymce.models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Event',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('event_title', models.TextField()),
                ('event_desc', tinymce.models.HTMLField(blank=True, null=True)),
                ('event_date', models.DateTimeField(blank=True, null=True)),
                ('event_location', models.TextField(blank=True, default='Gangolli - karnataka.', null=True)),
                ('event_image', models.ImageField(blank=True, help_text='Best Image Resolution width: 580 x Height: 565', null=True, upload_to='images-try/')),
            ],
            options={
                'verbose_name': 'Event',
                'verbose_name_plural': 'All Event',
                'ordering': ['-pk'],
            },
        ),
        migrations.CreateModel(
            name='MailLog',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('mFrom', models.TextField(verbose_name='Mail From')),
                ('to', models.TextField(verbose_name='Mail To')),
                ('subject', models.TextField(verbose_name='Subject')),
                ('body', models.TextField(verbose_name='Mail Body')),
                ('sent_at', models.DateTimeField(auto_now_add=True, verbose_name='Sent On')),
                ('queue', models.BooleanField(default=True, verbose_name='Queued')),
            ],
            options={
                'verbose_name': 'Mail',
                'verbose_name_plural': 'All Mails',
                'ordering': ['-pk'],
            },
        ),
        migrations.CreateModel(
            name='Staff',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('person_name', models.TextField()),
                ('person_title', models.TextField(blank=True, null=True)),
                ('person_occupation', models.TextField(blank=True, null=True)),
                ('person_image', models.ImageField(blank=True, null=True, upload_to='')),
            ],
            options={
                'verbose_name': 'Staff',
                'verbose_name_plural': 'All Staff',
                'ordering': ['-pk'],
            },
        ),
        migrations.CreateModel(
            name='EventImages',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('images', models.ImageField(blank=True, help_text='Best Image Resolution width: 580 x Height: 565', null=True, upload_to='')),
                ('event', models.ForeignKey(default=None, on_delete=django.db.models.deletion.CASCADE, to='base.event')),
            ],
        ),
    ]
